// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThienNguyenAPI.Data;

#nullable disable

namespace ThienNguyenAPI.Migrations
{
    [DbContext(typeof(ThienNguyenContext))]
    partial class ThienNguyenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBaiViet")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiBinhLuan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBinhLuan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.BaiViet", b =>
                {
                    b.Property<int>("IdBv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBv"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<int?>("IdChienDich")
                        .HasColumnType("int")
                        .HasColumnName("id_chien_dich");

                    b.Property<int?>("IdNguoiDang")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dang");

                    b.Property<DateTime?>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dang")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("SoLuotBinhLuan")
                        .HasColumnType("int")
                        .HasColumnName("SoLuotBinhLuan");

                    b.Property<int>("SoLuotThich")
                        .HasColumnType("int")
                        .HasColumnName("SoLuotThich");

                    b.HasKey("IdBv")
                        .HasName("PK__BaiViet__00B7D10485BAC77F");

                    b.HasIndex("IdChienDich");

                    b.HasIndex("IdNguoiDang");

                    b.ToTable("BaiViet", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.BaoCao", b =>
                {
                    b.Property<int>("IdBc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBc"));

                    b.Property<int?>("IdCd")
                        .HasColumnType("int")
                        .HasColumnName("id_cd");

                    b.Property<int?>("IdNd")
                        .HasColumnType("int")
                        .HasColumnName("id_nd");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_gui")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("noi_dung");

                    b.HasKey("IdBc")
                        .HasName("PK__BaoCao__00B7D117AFA82980");

                    b.HasIndex("IdCd");

                    b.HasIndex("IdNd");

                    b.ToTable("BaoCao", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.ChienDich", b =>
                {
                    b.Property<int>("IdCd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCd"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_chi");

                    b.Property<int?>("IdDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("id_danh_muc");

                    b.Property<int?>("IdNguoiToChuc")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_to_chuc");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quan_huyen");

                    b.Property<decimal?>("SoTienHienTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("so_tien_hien_tai");

                    b.Property<decimal?>("SoTienMucTieu")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("so_tien_muc_tieu");

                    b.Property<string>("TenCd")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_cd");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tinh_thanh");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdCd")
                        .HasName("PK__ChienDic__00B7DEF7386E9E84");

                    b.HasIndex("IdDanhMuc");

                    b.HasIndex("IdNguoiToChuc");

                    b.ToTable("ChienDich", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.DanhMuc", b =>
                {
                    b.Property<int>("IdDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dm");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDm"));

                    b.Property<string>("TenDm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_dm");

                    b.HasKey("IdDm")
                        .HasName("PK__DanhMuc__00B7C6D26273FE3F");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.GiaoDich", b =>
                {
                    b.Property<int>("IdGd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_gd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGd"));

                    b.Property<int?>("IdQg")
                        .HasColumnType("int")
                        .HasColumnName("id_qg");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phuong_thuc");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdGd")
                        .HasName("PK__GiaoDich__00B7FE789B2CA3D7");

                    b.HasIndex("IdQg");

                    b.ToTable("GiaoDich", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.NguoiDung", b =>
                {
                    b.Property<int>("IdNd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_nd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNd"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("hoat_dong")
                        .HasColumnName("trang_thai");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vai_tro");

                    b.HasKey("IdNd")
                        .HasName("PK__NguoiDun__0148B3BF9EE5EF75");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__AB6E6164D2734D55")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.QuyenGop", b =>
                {
                    b.Property<int>("IdQg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_qg");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQg"));

                    b.Property<int?>("IdCd")
                        .HasColumnType("int")
                        .HasColumnName("id_cd");

                    b.Property<int?>("IdNd")
                        .HasColumnType("int")
                        .HasColumnName("id_nd");

                    b.Property<string>("LoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("loi_nhan");

                    b.Property<DateTime?>("NgayQuyenGop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_quyen_gop")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("so_tien");

                    b.HasKey("IdQg")
                        .HasName("PK__QuyenGop__0148AB2428A1610A");

                    b.HasIndex("IdCd");

                    b.HasIndex("IdNd");

                    b.ToTable("QuyenGop", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.TepDinhKem", b =>
                {
                    b.Property<int>("IdTep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tep");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTep"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duong_dan");

                    b.Property<int?>("IdCd")
                        .HasColumnType("int")
                        .HasColumnName("id_cd");

                    b.Property<string>("LoaiTep")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_tep");

                    b.HasKey("IdTep")
                        .HasName("PK__TepDinhK__6A29A77BECD9F10F");

                    b.HasIndex("IdCd");

                    b.ToTable("TepDinhKem", (string)null);
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.BaiViet", b =>
                {
                    b.HasOne("ThienNguyenAPI.Data.ChienDich", "IdChienDichNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("IdChienDich")
                        .HasConstraintName("FK__BaiViet__id_chie__534D60F1");

                    b.HasOne("ThienNguyenAPI.Data.NguoiDung", "IdNguoiDangNavigation")
                        .WithMany("BaiViets")
                        .HasForeignKey("IdNguoiDang")
                        .HasConstraintName("FK__BaiViet__id_nguo__52593CB8");

                    b.Navigation("IdChienDichNavigation");

                    b.Navigation("IdNguoiDangNavigation");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.BaoCao", b =>
                {
                    b.HasOne("ThienNguyenAPI.Data.ChienDich", "IdCdNavigation")
                        .WithMany("BaoCaos")
                        .HasForeignKey("IdCd")
                        .HasConstraintName("FK__BaoCao__id_cd__4D94879B");

                    b.HasOne("ThienNguyenAPI.Data.NguoiDung", "IdNdNavigation")
                        .WithMany("BaoCaos")
                        .HasForeignKey("IdNd")
                        .HasConstraintName("FK__BaoCao__id_nd__4E88ABD4");

                    b.Navigation("IdCdNavigation");

                    b.Navigation("IdNdNavigation");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.ChienDich", b =>
                {
                    b.HasOne("ThienNguyenAPI.Data.DanhMuc", "IdDanhMucNavigation")
                        .WithMany("ChienDiches")
                        .HasForeignKey("IdDanhMuc")
                        .HasConstraintName("FK__ChienDich__id_da__3E52440B");

                    b.HasOne("ThienNguyenAPI.Data.NguoiDung", "IdNguoiToChucNavigation")
                        .WithMany("ChienDiches")
                        .HasForeignKey("IdNguoiToChuc")
                        .HasConstraintName("FK__ChienDich__id_ng__3D5E1FD2");

                    b.Navigation("IdDanhMucNavigation");

                    b.Navigation("IdNguoiToChucNavigation");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.GiaoDich", b =>
                {
                    b.HasOne("ThienNguyenAPI.Data.QuyenGop", "IdQgNavigation")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("IdQg")
                        .HasConstraintName("FK__GiaoDich__id_qg__46E78A0C");

                    b.Navigation("IdQgNavigation");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.QuyenGop", b =>
                {
                    b.HasOne("ThienNguyenAPI.Data.ChienDich", "IdCdNavigation")
                        .WithMany("QuyenGops")
                        .HasForeignKey("IdCd")
                        .HasConstraintName("FK__QuyenGop__id_cd__4222D4EF");

                    b.HasOne("ThienNguyenAPI.Data.NguoiDung", "IdNdNavigation")
                        .WithMany("QuyenGops")
                        .HasForeignKey("IdNd")
                        .HasConstraintName("FK__QuyenGop__id_nd__4316F928");

                    b.Navigation("IdCdNavigation");

                    b.Navigation("IdNdNavigation");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.TepDinhKem", b =>
                {
                    b.HasOne("ThienNguyenAPI.Data.ChienDich", "IdCdNavigation")
                        .WithMany("TepDinhKems")
                        .HasForeignKey("IdCd")
                        .HasConstraintName("FK__TepDinhKe__id_cd__4AB81AF0");

                    b.Navigation("IdCdNavigation");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.ChienDich", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("BaoCaos");

                    b.Navigation("QuyenGops");

                    b.Navigation("TepDinhKems");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.DanhMuc", b =>
                {
                    b.Navigation("ChienDiches");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("BaoCaos");

                    b.Navigation("ChienDiches");

                    b.Navigation("QuyenGops");
                });

            modelBuilder.Entity("ThienNguyenAPI.Data.QuyenGop", b =>
                {
                    b.Navigation("GiaoDiches");
                });
#pragma warning restore 612, 618
        }
    }
}
